import React from "react";
export const metadata = {
  title: "Veridia",
  description: "Generated by create next app",
};




export default function DashboardLayout({children}){
  return(
    <div>
        {children}
    </div>
  )
}