# netlify.toml

[build]
  # The command to run to build your Astro project.
  command = "npm run build"

  # The directory that contains the deployable static assets (your frontend HTML, CSS, JS).
  # When using @astrojs/node with output: 'server', Astro puts static assets in 'dist/client'.
  publish = "dist/client"

# This section configures Netlify Functions (or serverless functions).
[functions]
  # The directory where Astro's Node adapter places the server-side build output.
  # This is typically 'dist/server'.
  directory = "dist/server"

  # REMOVED: main = "entry.mjs"
  # This line was causing the error. Netlify typically expects the main handler file
  # (like 'entry.mjs' or 'index.js') to be directly present within the 'directory'
  # specified above, and it will automatically detect it.
  # You do NOT need a 'main' property here for the primary server function.

# This section sets up redirects/rewrites.
# For an SSR application, you typically want all requests to be handled by your
# serverless function, which then serves the correct page (static or dynamic).
[[redirects]]
  from = "/*" # Match all incoming requests
  to = "/.netlify/functions/entry" # Rewrite to your serverless function's endpoint
  status = 200 # Return a 200 OK status for successful rewrites
  force = true # Force the rewrite, even if a static file exists (important for SSR)

# You might also need to set environment variables for your build or runtime.
[build.environment]
  # Example: Make your backend API URL available to your frontend build.
  # This corresponds to `import.meta.env.PUBLIC_VERIDIA_API_POST` in your Astro code.
  # Replace with your actual deployed backend URL.
  PUBLIC_VERIDIA_API_POST = "https://webanalyzer-veridia.onrender.com/web-analyzer" # Replace with your deployed backend URL
